SYS-344: Added `/is-alive` and `/is-healthy` endpoints
shardeum/shardeum pull request #117
Opened 2024-08-02 22:28 UTC by asyed94

2024-08-05 15:34 UTC, soniasingla submitted a review, later dismissed

2024-08-07 17:37 UTC, chrypnotoad requested changes
new readme content shouldn't be in the `Stopping and Cleaning Up` section

2024-08-07 17:37 UTC, chrypnotoad commented on README.md
> +For usage instructions and available options for the shardus command-line tool, run `shardus --help`
This seems to be in the wrong spot. This section is `Stopping and Cleaning up` but this new content is about starting a network

2024-08-07 17:37 UTC, chrypnotoad commented on README.md
> +
This also seems to be inserted in the wrong section

2024-08-07 19:15 UTC, chrypnotoad approved these changes

2024-08-07 19:30 UTC, mssabr01 approved these changes

2024-08-07 19:32 UTC, merged