RED-304: Fix restore network caused by early shardus use
shardeum/shardeum pull request #174
Opened 2024-09-11 21:55 UTC by urnotsam

….crypto is not available at start up

2024-09-11 23:03 UTC, ahmxdiqbal approved these changes, later dismissed

2024-09-11 23:16 UTC, mssabr01 requested changes

2024-09-11 23:16 UTC, mssabr01 commented on src/index.ts
> +      const isResponseVerified = verify(res.data)
We have the expected public key of the archiver from the archiver list. Please use this as the expected pk and do not trust the pk that is included in the returned object

const isResponseVerified = verify(res.data, archiver.publicKey)

2024-09-12 00:02 UTC, mssabr01 approved these changes

2024-09-14 21:06 UTC, merged