feat: add functions for safe account balance arithmetic
shardeum/shardeum pull request #54
Opened 2024-06-11 12:46 UTC by tanuj-shardeum

2024-06-14 07:01 UTC, jairajdev requested changes

2024-06-14 07:01 UTC, jairajdev commented on src/utils/safeMath.ts
> +  static addNumberBalance(currentBalance: number, amountToAdd: number): number {
I think we can remove this as we 're not using it anymore.

2024-06-14 07:01 UTC, jairajdev commented on src/utils/safeMath.ts
> +  static subtractNumberBalance(currentBalance: number, amountToSubtract: number): number {
Same here, I think we can remove.

2024-06-14 07:35 UTC, tanuj-shardeum commented on src/utils/safeMath.ts
> +  static addNumberBalance(currentBalance: number, amountToAdd: number): number {
Done

2024-07-02 16:54 UTC, jairajdev approved these changes, later dismissed

2024-08-18 03:31 UTC, merged