Green 86 ajv first endpoint validator repo
shardeum/shardeum pull request #56
Opened 2024-06-12 10:01 UTC by tonititi

Add the AJV verification for the 'inject' endpoint of validator

2024-06-19 04:14 UTC, arhamj requested changes

2024-06-19 04:14 UTC, arhamj commented on src/types/InjectReq.ts
Why do we need these ser/de methods? I don't see them being used.

2024-06-19 04:14 UTC, arhamj commented on src/types/InjectResp.ts
ser/de methods not needed

2024-06-19 04:14 UTC, arhamj commented on src/types/ajv/InjectResp.ts
> +export const schemaInjectResponse = {
Add unit test to ensure this schema works as expected

2024-06-19 04:14 UTC, arhamj commented on src/types/ajv/InjectReq.ts
> +export const schemaInjectReq = {
Add unit test to ensure this schema works as expected

2024-07-03 08:48 UTC, S0naliThakur requested changes

2024-07-03 08:48 UTC, S0naliThakur commented on src/utils/serialization/VectorBufferStream.ts
> +    private buffer: Buffer
Use VectorBufferStream from shardus core. Request you to test out the chenges in a local nw

2024-07-03 08:48 UTC, S0naliThakur commented on src/types/ajv/InjectReq.ts
> +  addSchema('InjectReq', schemaInjectReq)
Can consider creating enum for schema names 'InjectReq' and 'InjectResp'

2024-07-03 11:15 UTC, S0naliThakur commented
Also remove extra comments from the tests

2024-07-03 11:17 UTC, S0naliThakur requested changes

2024-07-03 11:17 UTC, S0naliThakur commented on src/utils/serialization/VectorBufferStream.ts
> +    private buffer: Buffer
Use VectorBufferStream from shardus core. Request you to test out the chenges in a local nw

2024-07-09 06:05 UTC, S0naliThakur requested changes

2024-07-09 06:05 UTC, S0naliThakur commented on src/utils/serialization/VectorBufferStream.ts
> +export class VectorBufferStream {
Unused code. Remove this

2024-07-09 06:05 UTC, S0naliThakur commented on package.json
> +    "test-ajv": "jest"
can reuse test only

2024-07-09 06:05 UTC, S0naliThakur commented on test/unit/src/types/InjectReq.test.ts
> +            console.log('res', res!)
remove extra console logs, unnecessary comments from all the unit tests. Some tests fail, fix them too

2024-08-16 06:48 UTC, closed without merging