add flag to toggle reward txs
shardeum/shardeum pull request #64
Opened 2024-06-25 01:49 UTC by ahmxdiqbal

2024-06-25 13:31 UTC, urnotsam approved these changes, later dismissed

2024-06-25 16:36 UTC, urnotsam submitted a review, later dismissed

2024-08-20 22:11 UTC, afostr requested changes
please switch from a flag to a NetworkParameters.  
I think we can add a new group to NetworkParameters called utilityFlags
i.e.
, 
  utilityFlags: {
    enableNodeRewards: true,
    
  }
  
  Also requested.  we are blocking on the TX init, but we should also fail in both the apply verification and verifyTxnFields  for these two TXs.   This way some joker will be blocked if they edit their node to submit  anyway

2024-08-21 21:58 UTC, urnotsam approved these changes, later dismissed

2024-08-21 22:19 UTC, urnotsam approved these changes

2024-08-22 00:01 UTC, merged